spring:
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-db:3306/core
    username: root
    password: BR-10h8352
  jpa:
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
